name: freqtrade
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_freqaitorch
    environment:
      - FREQTRADE__EXCHANGE__KEY=${FREQTRADE__EXCHANGE__KEY}
      - FREQTRADE__EXCHANGE__SECRET=${FREQTRADE__EXCHANGE__SECRET}
      - FREQTRADE__TELEGRAM__TOKEN=${FREQTRADE__TELEGRAM__TOKEN}
      - FREQTRADE__TELEGRAM__CHAT_ID=${FREQTRADE__TELEGRAM__CHAT_ID}

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # restart: unless-stopped
    restart: no
    container_name: bybit
    volumes:
      - "./bybit:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8080"
    #entrypoint: sh # Reverted
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --freqaimodel XGBoostRegressor
      --strategy MainStrategy